v0.3.3   * [doc] `trl` now has a man page (if manually installed, use `trl --man`);           `trl -h` now just prints concise usage information.

diff --git a/bin/trl b/bin/trl
--- a/bin/trl
+++ b/bin/trl
@@ -1,11 +1,103 @@
 #!/usr/bin/env bash
 
-kTHIS_NAME=$(basename "$BASH_SOURCE")
+# --- STANDARD SCRIPT-GLOBAL CONSTANTS
 
-unset CDPATH  # to prevent unpredictable `cd` behavior
+kTHIS_NAME=${BASH_SOURCE##*/}
+kTHIS_HOMEPAGE='https://github.com/mklement0/trl'
+kTHIS_VERSION='v0.3.3' # NOTE: This assignment is automatically updated by `make version VER=<newVer>` - DO keep the 'v' prefix.
 
-# Output version number and exit, if requested. Note that the `ver='...'` statement is automatically updated by `make version VER=<newVer>` - DO keep the 'v' suffix in the variable _definition_.
-[[ $1 == '--version' ]] && { declare ver='v0.3.2'; echo "$kTHIS_NAME ${ver}"$'\nFor license information and more, visit https://github.com/mklement0/trl'; exit 0; }
+unset CDPATH  # To prevent unexpected `cd` behavior.
+
+# --- Begin: STANDARD HELPER FUNCTIONS
+
+die() { echo "$kTHIS_NAME: ERROR: ${1:-"ABORTING due to unexpected error."}" 1>&2; exit ${2:-1}; }
+dieSyntax() { echo "$kTHIS_NAME: ARGUMENT ERROR: ${1:-"Invalid argument(s) specified."} Use -h for help." 1>&2; exit 2; }
+
+# SYNOPSIS
+#   openUrl <url>
+# DESCRIPTION
+#   Opens the specified URL in the system's default browser.
+openUrl() {
+  local url=$1 platform=$(uname) cmd=()
+  case $platform in
+    'Darwin') # OSX
+      cmd=( open "$url" )
+      ;;
+    'CYGWIN_'*) # Cygwin on Windows; must call cmd.exe with its `start` builtin
+      cmd=( cmd.exe /c start '' "$url " )  # !! Note the required trailing space.
+      ;;
+    'MINGW32_'*) # MSYS or Git Bash on Windows; they come with a Unix `start` binary
+      cmd=( start '' "$url" )
+      ;;
+    *) # Otherwise, assume a Freedesktop-compliant OS, which includes many Linux distros, PC-BSD, OpenSolaris, ...
+      cmd=( xdg-open "$url" )
+      ;; 
+  esac
+  "${cmd[@]}" || { echo "Cannot locate or failed to open default browser; please go to '$url' manually." >&2; return 1; }
+}
+
+# Prints the embedded Markdown-formatted man-page source to stdout.
+printManPageSource() {
+  sed -n -e $'/^: <<\'EOF_MAN_PAGE\'/,/^EOF_MAN_PAGE/ { s///; t\np;}' "$BASH_SOURCE"
+}
+
+# Opens the man page, if installed; otherwise, tries to display the embedded Markdown-formatted man-page source; if all else fails: tries to display the man page online.
+openManPage() {
+  local pager embeddedText 
+  if ! man 1 "$kTHIS_NAME" 2>/dev/null; then
+    # 2nd attempt: if present, display the embedded Markdown-formatted man-page source
+    embeddedText=$(printManPageSource)
+    if [[ -n $embeddedText ]]; then
+      pager='more'
+      command -v less &>/dev/null && pager='less' # see if the non-standard `less` is available, because it's preferable to the POSIX utility `more`
+      printf '%s\n' "$embeddedText" | "$pager"
+    else # 3rd attempt: open the the man page on the utility's website
+      openUrl "${kTHIS_HOMEPAGE}/doc/${kTHIS_NAME}.md"
+    fi
+  fi  
+}
+
+# Prints the contents of the synopsis chapter of the embedded Markdown-formatted man-page source for quick reference.
+printUsage() {
+  local embeddedText
+  # Extract usage information from the SYNOPSIS chapter of the embedded Markdown-formatted man-page source.
+  embeddedText=$(sed -n -e $'/^: <<\'EOF_MAN_PAGE\'/,/^EOF_MAN_PAGE/!d; /^## SYNOPSIS$/,/^#/{ s///; t\np; }' "$BASH_SOURCE")
+  if [[ -n $embeddedText ]]; then
+    # Print extracted synopsis chapter - remove backticks for uncluttered display.
+    printf '%s\n\n' "$embeddedText" | tr -d '`'
+  else # No SYNOPIS chapter found; fall back to displaying the man page.
+    echo "WARNING: usage information not found; opening man page instead." >&2
+    openManPage
+  fi
+}
+
+# --- End: STANDARD HELPER FUNCTIONS
+
+# ---  PROCESS STANDARD, OUTPUT-INFO-THEN-EXIT OPTIONS.
+case $1 in
+  --version)
+    # Output version number and exit, if requested.
+    echo "$kTHIS_NAME $kTHIS_VERSION"$'\nFor license information and more, visit '"$kTHIS_HOMEPAGE"; exit 0
+    ;;
+  -h|--help)
+    # Print usage information and exit.
+    printUsage; exit
+    ;;
+  --man)
+    # Display the manual page and exit, falling back to printing the embedded man-page source.
+    openManPage; exit
+    ;;
+  --man-source) # private option, used by `make update-man`
+    # Print raw, embedded Markdown-formatted man-page source and exit
+    printManPageSource; exit
+    ;;
+  --home)
+    # Open the home page and exit.
+    openUrl "$kTHIS_HOMEPAGE"; exit
+    ;;
+esac
+
+# --- MAIN BODY
 
 # --- BEGIN: functions
 
@@ -55,105 +147,6 @@ ltrimSingleLine() {
 }
 
 # --- END: functions
-
-
-# Command-line help.
-if [[ $1 == '--help' || $1 == '-h' ]]; then
-  cat <<EOF
-SYNOPSIS
-  $kTHIS_NAME [-s inSep] [-S outSep] [-k|-D outDelim] [-W wrapText] [-R ors] [text ...]
-
-DESCRIPTION
-  $kTHIS_NAME *tr*ansforms *l*ists of unquoted and/or quoted strings, by
-  default between single- and multi-line forms.
-  Separators, delimiters, and a wrapper string are configurable.
-  
-  Both single- and double-quotes are recognized as input item delimiters.
-  
-  Caveats:
-   - Unbalanced single- or double-quotes in the input break parsing and
-     result in unpredictable output.
-   - While \' and \" are recognized as literal single- and double-quotes in
-     the input, they are output as literals without (re-)escaping; the only
-     exception is \' inside a single-quoted string in the input, which outputs
-     \' as well.
-
-  Input is provided via one or more operands or, in their absence, via stdin.
-  To disambiguate operands from options, precede operands with '--' as a
-  separate argument.
-  
-  Sensible defaults are used for options that aren't explicitly specified; 
-  their values depend on whether the input is single- or multi-line:
-  Single-line input:
-    List items are assumed to be separated with whitespace, a comma, or 
-    a comma followed by whitespace.
-    They are transformed into multi-line output with each item on its own
-    line, stripped of surrounding quotes.
-  Multi-line input:
-    List items are assumed to be each on a separate line.
-    They are transformed into a single-line list with items double-quoted
-    and separated by a comma followed by a space.
-  Explicitly specified options override the behavior described.
-
-  Some options described below come in two flavors:
-    - lowercase options such as -s describe the *input*
-    - corresponding uppercase options such as -S control the *output*
-
-  With the exception of -s, which accepts a Perl regular expression to
-  describe the separators between input items, options with arguments expect
-  literals rather than escape sequences; if needed, use ANSI C-quoted strings
-  in Bash, Ksh, or Zsh to create literal control characters; e.g.,
-  $'\n' and $'\t' create a literal newline and tab, respectively.
-
-    -k
-      Keeps all items in their input form, whether quoted or unquoted; the
-      default is to remove quoting on input processing; double-quoting is
-      by default applied on *output* when transforming a multi-line list to a
-      single-line list; to unconditionally produce unquoted items, use
-      -D '', to enforce a uniform quoting character, use -D <delim>.
-    -s inSep
-      Specifies the input item separator, i.e., what separates items in the
-      input, using a Perl regular expression. Note that *runs* of matches
-      (i.e., one or more contiguous instances) are invariably considered a
-      *single* separator.
-    -S outSep
-      Specifies the output item separator, i.e., how to separate the items
-      on output, irrespective of what separated them in the input.
-    -D outDelim
-      Specifies the delimiter to put around the output items; this may be
-      any string, but note that on *input* only single- and double-quotes
-      are recognized; cannot be combined with -k.
-      Use -D '' to make all output items unquoted.
-      If a single char. is specified, it is used as both the opening and 
-      closing delimiter; otherwise, the first *half* of the specified string
-      is used as the opening delimiter, and the second half as the closing one.
-    -W wrapText
-      Specifies output wrapper text to place around the entire output list,
-      including  desired whitespace, if any: if a single char. is specified,
-      that char. is used both before and the after the output list; otherwise,
-      the first *half* of the text is placed before, and the second one after;
-      if the output list is multi-line, a newline is appended / prepended to
-      the opening/closing string.
-    -R ors
-      Specifies the output record separator, which only applies to multi-line
-      input whose lines contain multiple items each: by default, the output
-      record separator is set to the same value as the input item separator,
-      so that a multi-line list results in a uniformly separated single-line
-      list. Specify -R $'\n' to instead retain the line breaks from the
-      input (while transforming the items on each line), or pass an
-      alternative separator to replace them.
-
-PREREQUISITES
-  Perl 5 must be installed.
-
-EXAMPLES
-  $kTHIS_NAME '"one", "two", "three"' # -> $'one\ntwo\three'
-  $kTHIS_NAME <<<$'one\ntwo\nthree' # -> '"one", "two", "three"'
-  $kTHIS_NAME -W '(  )' -S ' ' -D '' '"one","two","three"' # -> '( one two three )'
-  $kTHIS_NAME -s '[() -]' -S , '(789) 123-456' # -> '789,123,456'
-EOF
-    exit 0
-fi
 
 # Make sure that Perl is available.
 [[ -n $(command -v perl) ]] || die "This utility requires Perl. Executable \`perl\` cannot be located."
@@ -329,3 +322,218 @@ transform  < <(printf %s "$txt") || die
 
 exit 0
 
+####
+# MAN PAGE MARKDOWN SOURCE
+#  - Place a Markdown-formatted version of the man page for this script
+#    inside the here-document below.
+#    The document must be formatted to look good in all 3 viewing scenarios:
+#     - as a man page, after conversion to ROFF with marked-man
+#     - as plain text (raw Markdown source)
+#     - as HTML (rendered Markdown)
+#  Markdown formatting tips:
+#   - GENERAL
+#     To support plain-text rendering in the terminal, limit all lines to 80 chars.,
+#     and, for similar rendering as HTML, *end every line with 2 trailing spaces*.
+#   - HEADINGS
+#     - For better plain-text rendering, leave an empty line after a heading
+#       marked-man will remove it from the ROFF version.
+#     - The first heading must be a level-1 heading containing the utility
+#       name and very brief description; append the manual-section number 
+#       directly to the CLI name; e.g.:
+#         # foo(1) - does bar
+#     - The 2nd, level-2 heading must be '## SYNOPSIS' and the chapter's body
+#       must render reasonably as plain text, because it is printed to stdout
+#       when  `-h`, `--help` is specified:
+#         Use 4-space indentation without markup for both the syntax line and the
+#         block of brief option descriptions; represent option-arguments and operands
+#         in angle brackets; e.g., '<foo>'
+#     - All other headings should be level-2 headings in ALL-CAPS.
+#   - TEXT
+#      - Use NO indentation for regular chapter text; if you do, it will 
+#        be indented further than list items.
+#      - Use 4-space indentation, as usual, for code blocks.
+#      - Markup character-styling markup translates to ROFF rendering as follows:
+#         `...` and **...** render as bolded (red) text
+#         _..._ and *...* render as word-individually underlined text
+#   - LISTS
+#      - Indent list items by 2 spaces for better plain-text viewing, but note
+#        that the ROFF generated by marked-man still renders them unindented.
+#      - End every list item (bullet point) itself with 2 trailing spaces too so
+#        that it renders on its own line.
+#      - Avoid associating more than 1 paragraph with a list item, if possible,
+#        because it requires the following trick, which hampers plain-text readability:
+#        Use '&nbsp;<space><space>' in lieu of an empty line.
+####
+: <<'EOF_MAN_PAGE'
+# trl(1) - transform lists of strings
+
+## SYNOPSIS
+
+Transform lists of unquoted and/or quoted strings.
+
+    trl [<options>] [<text>...]
+
+    -s <inSep>      input list separator 
+    -S <outSep>     output list separator
+    -k              keep input item delimiters
+    -D <outDelim>   output item delimiter (cannot be combined with -k)
+    -W <wrapText>   text to wrap the result list in
+    -R <ors>        output record separator (multi-line + multi-item-per-line
+                    input only)
+
+By default,
+
+ * a multi-line list is transformed to a single-line list with double-quoted  
+   items separated by a comma followed by a space.
+ * a single-line list is transformed to a multi-line list with unquoted items.
+
+Standard options: `--help`, `--man`, `--version`, `--home`
+
+## DESCRIPTION
+
+trl *tr*ansforms *l*ists of unquoted and/or quoted strings, by default between  
+single- and multi-line forms.  
+Separators, delimiters, and an optional wrapper string are configurable.
+
+Both single- and double-quotes are recognized as input item delimiters.
+
+**Caveats**:
+
+ * Unbalanced single- or double-quotes in the input break parsing and result  
+   in unpredictable output.
+ * While \' and \" are recognized as literal single- and double-quotes in  
+   the input, they are output as literals without escaping; the only  
+   exception is \' inside a single-quoted string in the input, which is output  
+   as \' as well.
+
+Input is provided via one or more operands or, in their absence, via stdin.  
+To disambiguate operands from options, precede operands with `--` as a  
+separate argument.
+
+Sensible defaults are used for options that aren't explicitly specified;   
+their values depend on whether the input is single- or multi-line:  
+
+  * Single-line input:  
+  List items are assumed to be separated with whitespace, a comma, or a comma  
+  followed by whitespace.  
+  They are transformed into multi-line output with each item on its own  
+  line, stripped of surrounding quotes.
+
+  * Multi-line input:  
+  List items are assumed to be each on a separate line.  
+  They are transformed into a single-line list with items double-quoted and  
+  separated by a comma followed by a space.  
+
+Explicitly specified options override the behavior described.
+
+## OPTIONS
+
+Some options described below come in two flavors:
+
+  * Lowercase options such as `-s` describe the *input*.
+  * [Corresponding] uppercase options such as `-S` control the *output*.
+
+With the exception of `-s`, which accepts a Perl regular expression to  
+describe the separators between input items, options with arguments expect  
+literals rather than escape sequences; if needed, use ANSI C-quoted strings  
+in Bash, Ksh, or Zsh to create literal control characters; e.g., `$'\n'` and  
+`$'\t'` create a literal newline and tab, respectively.
+
+  * `-k`, `--keep`  
+    Keeps all items in their input form, whether quoted or unquoted; the  
+    default is to remove quoting on input processing; double-quoting is  
+    by default applied on *output* when transforming a multi-line list to a  
+    single-line list; to unconditionally produce unquoted items, use  
+    `-D ''`, to enforce a uniform quoting character, use `-D <delim>`.  
+
+  * `-s <inSep>`, `--separator <inSep>`  
+    Specifies the input item separator, i.e., what separates items in the  
+    input, using a Perl regular expression. Note that *runs* of matches  
+    (i.e., one or more contiguous instances) are invariably considered a  
+    *single* separator.
+
+  * `-S <outSep>`, `--out-separator <outSep>`  
+    Specifies the output item separator, i.e., how to separate the items  
+    on output, irrespective of what separated them in the input.
+
+  * `-D <outDelim>`, `--out-delim <outDelim>`  
+    Specifies the delimiter to put around the output items; this may be  
+    any string, but note that on *input* only single- and double-quotes  
+    are recognized; cannot be combined with `-k`.  
+    Use `-D ''` to make all output items unquoted.  
+    If a single char. is specified, it is used as both the opening and  
+    closing delimiter; otherwise, the first *half* of the specified string  
+    is used as the opening delimiter, and the second half as the closing one.
+  
+  * `-W <wrapText>`, `--out-wrapper <wrapText>`  
+    Specifies output wrapper text to place around the entire output list,  
+    including  desired whitespace, if any: if a single char. is specified,  
+    that char. is used both before and the after the output list; otherwise,  
+    the first *half* of the text is placed before, and the second one after;  
+    if the output list is multi-line, a newline is appended / prepended to  
+    the opening/closing string.
+
+  * `-R <ors>`, `--out-rec-separator <ors>`  
+    Specifies the output record separator, which only applies to multi-line  
+    input whose lines contain multiple items each: by default, the output  
+    record separator is set to the same value as the input item separator,  
+    so that a multi-line list results in a uniformly separated single-line  
+    list. Specify `-R $'\n'` to instead retain the line breaks from the  
+    input (while transforming the items on each line), or pass an  
+    alternative separator to replace them.
+
+## STANDARD OPTIONS
+
+All standard options provide information only.
+
+ * `-h, --help`  
+   Prints the contents of the synopsis chapter to stdout for quick reference.
+
+ * `--man`  
+   Displays this manual page, which is a helpful alternative to using `man`,  
+   if the manual page isn't installed.
+
+ * `--version`  
+   Prints version information.
+  
+ * `--home`  
+   Opens this utility's home page in the system's default web browser.
+
+## PREREQUISITES
+
+Perl 5 must be installed.
+
+## LICENSE
+
+For license information, bug reports, and more, visit this utility's home page  
+by running `trl --home`
+
+## EXAMPLES
+
+The examples in part use ANSI C-quoted input strings (`$'...'`) for brevity,  
+which are supported in Bash, Ksh, and Zsh.  
+ 
+    # Default single-line to multi-line transformation.
+    $ trl '"one", "two", "three"'
+    one
+    two
+    three
+
+    # Default multi-line to single-line transformation.
+    $ trl <<<$'one\ntwo\nthree'
+    "one", "two", "three"
+
+    # Transform the argument list to a C-style array:
+    $ trl -S ', ' -D \" -W '{  }' one two three 'four (4)'
+    { "one", "two", "three", "four (4)" }
+
+    # Transform a list to multi-line form using a regex to identify items;
+    # US-format telephone number to CSV:
+    $ trl -s '[() -]' -S , '(789) 123-456'
+    789,123,456
+
+    # Transform a multi-line list with multiple items per line.
+    $ trl -s ' ' -R ' <-> '  <<<$'one two\nthree four'
+    "one", "two" <-> "three", "four"
+
+EOF_MAN_PAGE
